INSERT INTO PROPERTIES(NAME, VALUE) VALUES('use.http.proxy', 'Y');
INSERT INTO PROPERTIES(NAME, VALUE) VALUES('http.proxy.hostname', '127.0.0.1');
INSERT INTO PROPERTIES(NAME, VALUE) VALUES('http.proxy.port', '3128');
INSERT INTO PROPERTIES(NAME, VALUE) VALUES('server.api.key', 'AIzaSyCWANqNXq72mWW44dVtsFg4hF44F2GxdQ8');
INSERT INTO PROPERTIES(NAME, VALUE) VALUES('multicast.size', '1000');
INSERT INTO PROPERTIES(NAME, VALUE) VALUES('retries', '3');
INSERT INTO PROPERTIES(NAME, VALUE) VALUES('data.message.key', 'message');
INSERT INTO PROPERTIES(NAME, VALUE) VALUES('threads', '5');
