CREATE TABLE DEVICE_REGISTRATIONS (
  ID bigint NOT NULL,
  DECLARED_DEVICE_ID character varying(255) NOT NULL,
  REGISTRATION_ID character varying(255) NOT NULL,
  CONSTRAINT PK_DEVICE_REGISTRATIONS PRIMARY KEY (ID),
  CONSTRAINT UK_DEVICE_REGISTRATIONS_01 UNIQUE (REGISTRATION_ID)
);

CREATE TABLE PROPERTIES (
  NAME character varying(255) NOT NULL,
  VALUE character varying(255) NOT NULL,
  CONSTRAINT PK_PROPERTIES PRIMARY KEY (NAME)
);
